### ISSUE TITLE
Support for Neo4j 4.x (HTTP API)

### ISSUE THREAD

**Issue by hertzhaft** [johannessen/neo4j-driver-perl#6]
It would be good to have a working Perl driver for Neo4j 4.x; both `REST::Neo4p` and `Neo4j::Bolt` are not adapted yet, so `Neo4j::Driver` seems the best candidate to use, but there's also some issue at the moment:

```perl
use Neo4j::Driver;
my $uri = 'http://localhost:7474';
my $driver = Neo4j::Driver->new($uri)->basic_auth('neo4j', 'neo4j');
my $record = $driver->session->run('RETURN 1 AS one, 2 AS two');
```
produces:
Network error: 404

Some indications:
* the default database (for the community edition) is now called `neo4j` instead of `data` (/usr/share/perl5/site_perl/Neo4j/Driver/Transport/HTTP.pm, lines 27-30); in the enterprise edition multiple databases are possible.

* all `{ "statement" : }` objects need to be wrapped in a `"statements" : []` array

* if I understood the documentation correctly, by default basic authentication or authorization is not needed for the HTTP API (https://neo4j.com/docs/http-api/4.0/security/)

So far I haven't succeeded to get a functioning connection.

**Comment by johannessen** [comment]
Hi @hertzhaft, thanks a lot for your report!

> ```perl
> use Neo4j::Driver;
> my $uri = 'http://localhost:7474';
> my $driver = Neo4j::Driver->new($uri)->basic_auth('neo4j', 'neo4j');
> my $record = $driver->session->run('RETURN 1 AS one, 2 AS two');
> ```
> 
> produces:
> Network error: 404
> 
> Some indications:
> 
> * the default database (for the community edition) is now called `neo4j` instead of `data` (/usr/share/perl5/site_perl/Neo4j/Driver/Transport/HTTP.pm, lines 27-30); in the enterprise edition multiple databases are possible.

In earlier Neo4j versions, the database was called `graph.db`. `/db/data/` is/was simply a REST service endpoint.

I’ve been getting inconsistent results from those endpoints. Neo4j::Driver 0.15 uses the endpoints from Neo4j 2 and 3. Up until now, this seemed reliable even in Neo4j 4. Even now, I’m unable to reproduce your issue with Neo4j::Driver, and automated testing of Neo4j::Driver is also [successful](https://travis-ci.org/github/johannessen/neo4j-driver-perl/jobs/662818568) on a live 4.0.0 database using the “old” endpoints.

This would appear to indicate a possible issue with certain versions of the Neo4j server. I’ll look into it, but I’m afraid it’s going to take some time.

As a possible workaround to get Neo4j::Driver 0.15 working with your Neo4j server version, you could try manipulating the REST endpoints like this:

````perl
die unless $Neo4j::Driver::VERSION eq '0.15';
$Neo4j::Driver::Transport::HTTP::TRANSACTION_ENDPOINT = '/db/neo4j/tx';
$Neo4j::Driver::Transport::HTTP::COMMIT_ENDPOINT = '/db/neo4j/tx/commit';

my $driver = $Neo4j::Driver->new;
...
````

By the way, the enterprise edition is [not actively supported](https://metacpan.org/pod/Neo4j::Driver#BUGS) by Neo4j::Driver. That said, I think it *should* work fine as long as none of the more fancy features are being used.

Which exact Neo4j version are you currently running?
What kind of operating system are you running?

**Comment by johannessen** [comment]
> * all `{ "statement" : }` objects need to be wrapped in a `"statements" : []` array

That’s true, and I don’t see an issue with Neo4j::Driver here.
   

> * if I understood the documentation correctly, by default basic authentication or authorization is not needed for the HTTP API (https://neo4j.com/docs/http-api/4.0/security/)

If you see an issue with Neo4j::Driver here: Could you please clarify where exactly it seems to be?

(FWIW, the Neo4j documentation appears to be incorrect on this point. At present, the community edition still requires authentication by default. As the documentation for version 3.5 describes, [the default password `neo4j` must be changed after installation](https://neo4j.com/docs/http-api/3.5/security/#http-api-security-introduction) before the database can be used.)

**Comment by hertzhaft** [comment]
Thanks for your prompt reply! 

I did some debugging, and the problem is indeed not caused by Neo4j::Driver. I am running Neo4j 4.0.0 under ArchLinux (through the package neo4j-community 4.0.0-1), perl 5.30.2 and Neo4j::Driver 0.15. When the Neo4j package was recently upgraded from 3.5.3, the database was automatically migrated, but the old name `graph.db` was kept. That way I keep getting 404 errors from the HTTP API, because neither name is accepted in the URL. Because in the browser frontend everything worked, I suspected some error in the API call through Neo4j.Driver.

In the end I had to delete the old "graph.db" database and restart the service. Neo4j then creates a fresh "neo4j" database. And Neo4j::Driver works again, when I add the lines you mentioned above to my script:
```perl
$Neo4j::Driver::Transport::HTTP::TRANSACTION_ENDPOINT = '/db/neo4j/tx';
$Neo4j::Driver::Transport::HTTP::COMMIT_ENDPOINT = '/db/neo4j/tx/commit';
```
The `/db/data` endpoint doesn't seem to work anymore.

So I'd suggest two things:

a) mentioning those variables in the documentation (maybe even change the default value in the next version?), and 
b) adapting `Neo4j/Driver/Transport/HTTP.pm, line 148-154` so that it reports the detailed error messages from Neo4j that are returned in JSON format in `REST::Client->{_res}`, even when the response code is a 404. That would have got me on the right track a little sooner :-)

**Comment by johannessen** [comment]
Thanks for taking the time to explain the history of your Neo4j environment. I suspect the upgrade from Neo4j 3.5 to 4.0 somehow is what triggers this bug. But so far, I still can’t reproduce it (i. e., I don’t get 404s when using the old endpoints, even though my setup is quite similar to yours).

BTW, the [Neo4j Migration Guide](https://neo4j.com/docs/migration-guide/4.0/upgrade-single-instance/) explains how to successfully upgrade from 3.5 to 4.0 and keep using the `graph.db` database.

I’m glad you got Neo4j::Driver working by changing the endpoints!

But, clearly, users cannot be expected to fiddle around with those variables. It’s the driver’s job to figure out the correct endpoints automatically. That it evidently fails to do so in some cases must be considered a bug in Neo4j::Driver.

In order to resolve this, the driver needs to first determine whether the server major version is at least 4. If so, it needs to query the `system` database for the name of the default database, then use the result to construct the correct endpoint for that database. This shouldn’t be hard, but it will take a bit of time to implement properly.

In the meantime, I’ve released [Neo4j::Driver 0.16](https://metacpan.org/release/AJNN/Neo4j-Driver-0.16), which offers a new option to explicitly [select a database specified by name](https://metacpan.org/pod/release/AJNN/Neo4j-Driver-0.16/lib/Neo4j/Driver.pm#Database-selection). Using this option should work around the bug:

````perl
use Neo4j::Driver 0.16;
my $driver = Neo4j::Driver->new->basic_auth(...);

my $session = $driver->session( database => 'neo4j' );  # for Neo4j 4.x only
...
````

The endpoint variables have been renamed in this update. With the new `database` option, you shouldn’t need to change them anymore.

**Comment by hertzhaft** [comment]
Thank you very much! Works perfectly, I tested it.
As for the migration - it happened automatically with the Update of the Arch Linux package. Thanks for the pointer!

**Comment by johannessen** [comment]
Neo4j::Driver [0.17](https://metacpan.org/pod/release/AJNN/Neo4j-Driver-0.17/lib/Neo4j/Driver.pm) has just been released. The [`database`](https://metacpan.org/pod/Neo4j::Driver#session) option may still be used, but is no longer necessary for the Neo4j community edition. The driver now determines the default database automatically.

With that, I believe this bug to be resolved.
(Although I see now that I forgot to remove the mention of this bug from the module documentation…)
